AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an Amazon Linux 2 EC2 instance with some default settings'

Parameters:
  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmazonLinuxAMIID
      InstanceType: t3.nano
      SecurityGroups:
      - Ref: MySecurityGroup
      KeyName: 78596
      Tags:
        - Key: Owner
          Value: rob78596
        - Key: Name
          Value: rob78596
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 52.0.0.0/8

Outputs:
  InstanceId:
    Value:
      Ref: MyEC2Instance
  PublicIP:
    Value:
      Fn::GetAtt:
      - MyEC2Instance
      - PublicIp
