AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: rob78596test3
      AccessControl: PublicRead
      Tags:
        - Key: Owner
          Value: rob78596
